version: "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    environment:
      - PORT=3000
      - DB_IP=postgres
      - DB_USER=Ignatius
      - DB_PASSWORD=5555
      - SESSION_SECRET=xyzsermlcd
    depends_on:
      - postgres

  postgres:
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=5555
      - POSTGRES_USER=Ignatius
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: always
    environment:
      - REDIS_PASSWORD=5555
      - REDIS_URL=redis
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
