version: "3.9"
services:
  nginx:
    ports:
      - "3000:80"

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  mongo:
    image: mongo:6-jammy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=IgnatiusFrancis
      - MONGO_INITDB_ROOT_PASSWORD=62627777
    volumes:
      - mongo_data:/data/db
